
dubbo:
  protocol:
    name: dubbo
    port: 20888
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    name: provider-of-cart
  #scan:
    #base-packages: com.git.dubboprovider.service